# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e80ef2569002f2e1c05b2e0162103269a940d1979883c566a484da62ffcf7c564fb4f2da3109713b72391cff9dca7176beebc11674063b44ae2193a022281942

test:
  secret_key_base: 85403d1e32a87cc32db02954a44d20410619081d88cda59b76e221632597aabf1a9d2c851817e69cc3f0ea5c4b331bb34937de9b18d59f3e5666487ddea10ddf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
